[ADMIN] publication of MRA whitepaper
OpenManufacturingPlatform/MRA-Architectural-Considerations pull request #3
Opened 2021-05-24 18:14 UTC by jpradocueva

The latest changes was an update to the README file to add a link to the PDF and blog on the OMP website:

**Blog**: https://open-manufacturing.org/blog/2021/05/23/manufacturing-reference-architecture/
**PDF**: https://open-manufacturing.org/wp-content/uploads/sites/101/2021/05/OMP_Reference_Architecture_Whitepaper-17-May-21.pdf

2021-05-24 18:37 UTC, jpradocueva commented
License file update to "Patent-Policy-W3C-Mode" as described in the WG Charter.

2021-05-25 06:15 UTC, wrichter requested changes
Minor change requested: remove the TODO marker in README.md

2021-05-25 06:15 UTC, wrichter commented on README.md
> +**TODO - Adjust Whitepaper Download URL**
We should remove the TODO markers now that the URL has been adapted

2021-05-25 15:42 UTC, jpradocueva commented on README.md
> +**TODO - Adjust Whitepaper Download URL**
Ups! I will take care of it. Thanks for pointing it out. I thought that I did but clearly I didn't.

2021-05-25 16:06 UTC, jpradocueva commented
We need to merge this PR into production.
Today, Tuesday, May 25th at 10:00 am PDT, HubSpot will start an email campaign announcing the publication of the MRA whitepaper. The email will be sent to over 380 users in OMP HubSpot database.

2021-05-25 16:06 UTC, merged